spring:
  datasource:
    url: jdbc:h2:file:./camunda-h2-database
    driverClassName: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
  main:
    allow-bean-definition-overriding: true
camunda.bpm.admin-user:
  id: demo
  password: demo



